# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

project_name: sops

# xref: https://goreleaser.com/customization/hooks/
before:
  hooks:
    - go mod download

# xref: https://goreleaser.com/customization/env/
env:
  - CGO_ENABLED=0
  - PKG=github.com/getsops/sops/v3/version
  - COSIGN_YES=true

# xref: https://goreleaser.com/customization/reportsizes/
report_sizes: true

# xref: https://goreleaser.com/customization/build/
builds:
  - id: binary-linux
    main: ./cmd/sops
    binary: "{{ .ProjectName }}"
    flags:
      - -trimpath
      - -mod=readonly
    ldflags:
      - >
        -s -w
        -X {{ .Env.PKG }}.Version={{ .Version }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    # Modified timestamp on the binary, set to ensure reproducible builds.
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: binary-darwin
    main: ./cmd/sops
    binary: "{{ .ProjectName }}"
    flags:
      - -trimpath
      - -mod=readonly
    ldflags:
      - >
        -s -w
        -X {{ .Env.PKG }}.Version={{ .Version }}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    # Modified timestamp on the binary, set to ensure reproducible builds.
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: binary-windows
    main: ./cmd/sops
    binary: "{{ .ProjectName }}"
    flags:
      - -trimpath
      - -buildmode=pie
      - -mod=readonly
    ldflags:
      - >
        -s -w
        -X {{ .Env.PKG }}.Version={{ .Version }}
    goos:
      - windows
    goarch:
      - amd64
    # Modified timestamp on the binary, set to ensure reproducible builds.
    mod_timestamp: "{{ .CommitTimestamp }}"

# xref: https://goreleaser.com/customization/universalbinaries/
universal_binaries:
  - id: binary-darwin-universal
    ids:
      - binary-darwin
    name_template: '{{ .ProjectName }}'
    # We want to continue to ship individual binaries for darwin/amd64 and
    # darwin/arm64.
    replace: false
    # Modified timestamp on the binary, set to ensure reproducible builds.
    # NB: Available in (unreleased) GoReleaser >=1.20.0.
    # mod_timestamp: "{{ .CommitTimestamp }}"

# xref: https://goreleaser.com/customization/nfpm/
nfpms:
  - id: deb
    package_name: '{{ .ProjectName }}'
    file_name_template: '{{ .ConventionalFileName }}'
    vendor: CNCF SOPS
    homepage: https://github.com/{{ .Env.GITHUB_REPOSITORY }}
    maintainer: SOPS maintainers <cncf-SOPS-maintainers@lists.cncf.io>
    description: Simple and flexible tool for managing secrets
    license: MPL-2.0
    formats:
      - deb
      - rpm

# xref: https://goreleaser.com/customization/snapshots/
snapshot:
  name_template: "{{ incpatch .Version }}-dev-{{ .ShortCommit }}"

# xref: https://goreleaser.com/customization/archive/#disable-archiving
archives:
  - id: archive-unix
    format: binary
    builds:
      - binary-linux
      - binary-darwin
    # NB: specifically crafted to ensure compatibility with release artifacts < v3.8.0.
    name_template: '{{ .ProjectName }}-v{{ .Version }}.{{ .Os }}.{{ .Arch }}'

  - id: archive-windows
    format: binary
    builds:
      - binary-windows
    # NB: specifically crafted to ensure compatibility with release artifacts < v3.8.0.
    name_template: '{{ .ProjectName }}-v{{ .Version }}'

  - id: archive-darwin-universal
    format: binary
    builds:
      - binary-darwin-universal
    # NB: specifically crafted to ensure compatibility with release artifacts < v3.8.0.
    # We can't bundle this with the other unix archive, because .Arch becomes "all".
    # Before v3.8.0, this used to be _just_ the AMD64 binary.
    name_template: '{{ .ProjectName }}-v{{ .Version }}.darwin'

# xref: https://goreleaser.com/customization/checksum/
checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}.checksums.txt"
  algorithm: sha256
  ids:
    - archive-unix
    - archive-windows
    - archive-darwin-universal

# xref: https://goreleaser.com/customization/sbom/
sboms:
  - id: binary-sbom
    artifacts: binary
    documents:
      - "{{ .ArtifactName }}.spdx.sbom.json"

# xref: https://goreleaser.com/customization/sign/
signs:
  - cmd: cosign
    artifacts: checksum
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - "sign-blob"
      - "--output-signature"
      - "${artifact}.sig"
      - "--output-certificate"
      - "${artifact}.pem"
      - "${artifact}"
    output: true

# xref: https://goreleaser.com/customization/docker/
dockers:
  - image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-amd64'
      - 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-amd64'
    use: buildx
    goos: linux
    goarch: amd64
    ids:
      - binary-linux
    dockerfile: .release/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"

  - image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-arm64'
      - 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-arm64'
    use: buildx
    goos: linux
    goarch: arm64
    ids:
      - binary-linux
    dockerfile: .release/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"

  - image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-alpine-amd64'
      - 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-alpine-amd64'
    use: buildx
    goos: linux
    goarch: amd64
    ids:
      - binary-linux
    dockerfile: .release/alpine.Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"

  - image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-alpine-arm64'
      - 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-alpine-arm64'
    use: buildx
    goos: linux
    goarch: arm64
    ids:
      - binary-linux
    dockerfile: .release/alpine.Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"

# xref: https://goreleaser.com/customization/docker_manifest/
docker_manifests:
  - name_template: 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}'
    image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-amd64'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-arm64'

  - name_template: 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-alpine'
    image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-alpine-amd64'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-alpine-arm64'

  - name_template: 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}'
    image_templates:
      - 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-amd64'
      - 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-arm64'

  - name_template: 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-alpine'
    image_templates:
      - 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-alpine-amd64'
      - 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-alpine-arm64'

# xref: https://goreleaser.com/customization/docker_sign/
docker_signs:
  - cmd: cosign
    artifacts: all
    output: true
    args:
      - "sign"
      - "${artifact}@${digest}"

# xref: https://goreleaser.com/customization/changelog/
changelog:
  # xref: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options
  # xref: https://docs.github.com/en/free-pro-team@latest/rest/releases/releases?apiVersion=2022-11-28#generate-release-notes-content-for-a-release
  use: github-native

# xref: https://goreleaser.com/customization/release/
release:
  prerelease: auto
  header: |
    ## Container images

    Supported architectures: `linux/amd64` and `linux/arm64`.

    ### GitHub Container Registry

    - `ghrc.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}`
    - `ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-alpine`

    ### Quay.io

    - `quay.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}`
    - `quay.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }}-alpine`

    ### Verify container image signature

    The container images are signed with [Cosign](https://docs.sigstore.dev/cosign/overview/) using GitHub OIDC. To verify the signature of an image, run:

    ```shell
    cosign verify ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:v{{ .Version }} \
      --certificate-identity-regexp=https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }} \
      --certificate-oidc-issuer=https://token.actions.githubusercontent.com
    ```

    ### Verify container image provenance

    The container images include [SLSA provenance](https://slsa.dev/provenance/v0.2) attestations. For more information around the verification of this, please refer to the [`slsa-verifier` documentation](https://github.com/slsa-framework/slsa-verifier#containers).
