# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

project_name: sops

# xref: https://goreleaser.com/customization/hooks/
before:
  hooks:
    - go mod download
    - /usr/bin/env bash -c 'if [ -n "$(git --no-pager diff --exit-code go.mod go.sum)" ]; then exit 1; fi'

# xref: https://goreleaser.com/customization/env/
env:
  - CGO_ENABLED=0
  - PKG=github.com/getsops/sops/v3/version
  - COSIGN_YES=true

# xref: https://goreleaser.com/customization/reportsizes/
report_sizes: true

# xref: https://goreleaser.com/customization/build/
builds:
  - id: binary-linux
    main: ./cmd/sops
    # Specially crafted to ensure compatibility with release artifacts < v3.8.0.
    binary: "{{ .ProjectName }}-{{ .Version }}.{{ .Os }}.{{ .Arch }}"
    flags:
      - -v
      - -trimpath
    ldflags:
      - >
        -extldflags "-static" -s -w
        -X {{ .Env.PKG }}.Version={{ .Version }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    # Modified timestamp on the binary, set to ensure reproducible builds.
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: binary-darwin
    main: ./cmd/sops
    # Specially crafted to ensure compatibility with release artifacts < v3.8.0.
    binary: "{{ .ProjectName }}-{{ .Version }}.{{ .Os }}.{{ .Arch }}"
    flags:
      - -v
      - -trimpath
    ldflags:
      - >
        -extldflags "-static" -s -w
        -X {{ .Env.PKG }}.Version={{ .Version }}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    # Modified timestamp on the binary, set to ensure reproducible builds.
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: binary-windows
    main: ./cmd/sops
    # Specially crafted to ensure compatibility with release artifacts < v3.8.0.
    binary: "{{ .ProjectName }}-{{ .Version }}"
    flags:
      - -v
      - -trimpath
    ldflags:
      - >
        -extldflags "-static" -s -w
        -X {{ .Env.PKG }}.Version={{ .Version }}
    goos:
      - windows
    goarch:
      - amd64
    # Modified timestamp on the binary, set to ensure reproducible builds.
    mod_timestamp: "{{ .CommitTimestamp }}"

# xref: https://goreleaser.com/customization/universalbinaries/
universal_binaries:
  - ids:
      - binary-darwin
    # Specially crafted to ensure compatibility with release artifacts < v3.8.0.
    # Before v3.8.0, this used to be _just_ the AMD64 binary.
    name_template: '{{ .ProjectName }}-{{ .Version }}.darwin'
    replace: false

# xref: https://goreleaser.com/customization/nfpm/
nfpms:
  - id: deb
    package_name: '{{ .ProjectName }}'
    file_name_template: '{{ .ConventionalFileName }}'
    vendor: CNCF SOPS
    homepage: https://github.com/{{ .Env.GITHUB_REPOSITORY }}
    maintainer: SOPS maintainers <cncf-SOPS-maintainers@lists.cncf.io>
    description: Simple and flexible tool for managing secrets
    license: MPL-2.0
    formats:
      - deb
      - rpm

# xref: https://goreleaser.com/customization/snapshots/
snapshot:
  name_template: "{{ incpatch .Version }}-dev-{{ .ShortCommit }}"

# xref: https://goreleaser.com/customization/archive/#disable-archiving
archives:
  - id: binaries
    format: binary
    builds:
      - binary-linux
      - binary-darwin
      - binary-windows
    # NB: Binaries already have unique names to ensure compatibility with
    # release artifacts < v3.8.0.
    name_template: "{{ .Binary }}"

# xref: https://goreleaser.com/customization/checksum/
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}.checksums.txt"
  algorithm: sha256
  ids:
    - binaries

# xref: https://goreleaser.com/customization/sbom/
sboms:
  - id: binary-sbom
    artifacts: binary
    documents:
      - "${artifact}.spdx.sbom.json"

# xref: https://goreleaser.com/customization/sign/
signs:
  - cmd: cosign
    artifacts: checksum
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - "sign-blob"
      - "--output-signature"
      - "${artifact}.sig"
      - "--output-certificate"
      - "${artifact}.pem"
      - "${artifact}"
    output: true

# xref: https://goreleaser.com/customization/docker/
dockers:
  - image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-amd64'
      - 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-amd64'
    use: buildx
    goos: linux
    goarch: amd64
    ids:
      - binary-linux
    dockerfile: .release/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"

  - image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-arm64'
      - 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-arm64'
    use: buildx
    goos: linux
    goarch: arm64
    ids:
      - binary-linux
    dockerfile: .release/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"

  - image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-alpine-amd64'
      - 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-alpine-amd64'
    use: buildx
    goos: linux
    goarch: amd64
    ids:
      - binary-linux
    dockerfile: .release/alpine.Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"

  - image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-alpine-arm64'
      - 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-alpine-arm64'
    use: buildx
    goos: linux
    goarch: arm64
    ids:
      - binary-linux
    dockerfile: .release/alpine.Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"

# xref: https://goreleaser.com/customization/docker_manifest/
docker_manifests:
  - name_template: 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}'
    image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-amd64'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-arm64'

  - name_template: 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-alpine'
    image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-alpine-amd64'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-alpine-arm64'

  - name_template: 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}'
    image_templates:
      - 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-amd64'
      - 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-arm64'

  - name_template: 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-alpine'
    image_templates:
      - 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-alpine-amd64'
      - 'quay.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-alpine-arm64'

# xref: https://goreleaser.com/customization/docker_sign/
docker_signs:
  - cmd: cosign
    artifacts: all
    output: true
    args:
      - "sign"
      - "-a"
      - "GIT_SHA={{ .FullCommit }}"
      - "-a"
      - "GIT_TAG={{ .Tag }}"
      - "${artifact}@${digest}"

# xref: https://goreleaser.com/customization/changelog/
changelog:
  # xref: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options
  # xref: https://docs.github.com/en/free-pro-team@latest/rest/releases/releases?apiVersion=2022-11-28#generate-release-notes-content-for-a-release
  use: github-native

# xref: https://goreleaser.com/customization/release/
release:
  prerelease: auto
