{
  "revision": "20170812",
  "documentationLink": "https://developers.google.com/vault",
  "id": "vault:v1",
  "discoveryVersion": "v1",
  "version_module": true,
  "protocol": "rest",
  "canonicalName": "Vault",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ediscovery.readonly": {
          "description": "View your eDiscovery data"
        },
        "https://www.googleapis.com/auth/ediscovery": {
          "description": "Manage your eDiscovery data"
        }
      }
    }
  },
  "rootUrl": "https://vault.googleapis.com/",
  "ownerDomain": "google.com",
  "name": "vault",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "title": "Google Vault API",
  "ownerName": "Google",
  "resources": {
    "matters": {
      "methods": {
        "update": {
          "description": "Updates the specified matter.\nThis updates only the name and description of the matter, identified by\nmatter id. Changes to any other fields are ignored.\nReturns the default view of the matter.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}",
          "id": "vault.matters.update",
          "path": "v1/matters/{matterId}"
        },
        "delete": {
          "description": "Deletes the specified matter. Returns matter with updated state.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}",
          "path": "v1/matters/{matterId}",
          "id": "vault.matters.delete"
        },
        "list": {
          "description": "Lists matters the user has access to.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "flatPath": "v1/matters",
          "id": "vault.matters.list",
          "path": "v1/matters"
        },
        "addPermissions": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}:addPermissions",
          "id": "vault.matters.addPermissions",
          "path": "v1/matters/{matterId}:addPermissions",
          "description": "Adds an account as a matter collaborator."
        },
        "create": {
          "description": "Creates a new matter with the given name and description. The initial state\nis open, and the owner is the method caller. Returns the created matter\nwith default view.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters",
          "path": "v1/matters",
          "id": "vault.matters.create"
        },
        "reopen": {
          "flatPath": "v1/matters/{matterId}:reopen",
          "id": "vault.matters.reopen",
          "path": "v1/matters/{matterId}:reopen",
          "description": "Reopens the specified matter. Returns matter with updated state.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "removePermissions": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}:removePermissions",
          "id": "vault.matters.removePermissions",
          "path": "v1/matters/{matterId}:removePermissions",
          "description": "Removes an account as a matter collaborator."
        },
        "close": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}:close",
          "path": "v1/matters/{matterId}:close",
          "id": "vault.matters.close",
          "description": "Closes the specified matter. Returns matter with updated state.",
          "httpMethod": "POST"
        },
        "undelete": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}:undelete",
          "path": "v1/matters/{matterId}:undelete",
          "id": "vault.matters.undelete",
          "description": "Undeletes the specified matter. Returns matter with updated state."
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "flatPath": "v1/matters/{matterId}",
          "id": "vault.matters.get",
          "path": "v1/matters/{matterId}",
          "description": "Gets the specified matter."
        }
      },
      "resources": {
        "holds": {
          "methods": {
            "delete": {
              "description": "Removes a hold by ID. This will release any HeldAccounts on this Hold.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "id": "vault.matters.holds.delete",
              "path": "v1/matters/{matterId}/holds/{holdId}"
            },
            "list": {
              "description": "Lists holds within a matter. An empty page token in ListHoldsResponse\ndenotes no more holds to list.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "flatPath": "v1/matters/{matterId}/holds",
              "id": "vault.matters.holds.list",
              "path": "v1/matters/{matterId}/holds"
            },
            "get": {
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "id": "vault.matters.holds.get",
              "description": "Gets a hold by ID.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            },
            "update": {
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "id": "vault.matters.holds.update",
              "description": "Updates the OU and/or query parameters of a hold. You cannot add accounts\nto a hold that covers an OU, nor can you add OUs to a hold that covers\nindividual accounts. Accounts listed in the hold will be ignored."
            },
            "create": {
              "path": "v1/matters/{matterId}/holds",
              "id": "vault.matters.holds.create",
              "description": "Creates a hold in the given matter.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "flatPath": "v1/matters/{matterId}/holds"
            }
          },
          "resources": {
            "accounts": {
              "methods": {
                "delete": {
                  "description": "Removes a HeldAccount from a hold. If this request leaves the hold with\nno held accounts, the hold will not apply to any accounts.",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                  "id": "vault.matters.holds.accounts.delete",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery",
                    "https://www.googleapis.com/auth/ediscovery.readonly"
                  ],
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "id": "vault.matters.holds.accounts.list",
                  "description": "Lists HeldAccounts for a hold. This will only list individually specified\nheld accounts. If the hold is on an OU, then use\n\u003ca href=\"https://developers.google.com/admin-sdk/\"\u003eAdmin SDK\u003c/a\u003e\nto enumerate its members.",
                  "httpMethod": "GET"
                },
                "create": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "id": "vault.matters.holds.accounts.create",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "description": "Adds a HeldAccount to a hold. Accounts can only be added to a hold that\nhas no held_org_unit set. Attempting to add an account to an OU-based\nhold will result in an error."
                }
              }
            }
          }
        }
      }
    }
  },
  "version": "v1",
  "baseUrl": "https://vault.googleapis.com/",
  "kind": "discovery#restDescription",
  "description": "Archiving and eDiscovery for G Suite.",
  "servicePath": "",
  "basePath": ""
}
