creation_rules:
    - path_regex: test_roundtrip_keygroups.yaml
      key_groups:
      - pgp:
        - FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4
      - pgp:
        - D7229043384BCC60326C6FB9D8720D957C3D3074
    - path_regex: test_roundtrip_keygroups_missing_decryption_key.yaml
      key_groups:
      - pgp:
        - FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4
      - pgp:
        - B611A2F9F11D0FF82568805119F9B5DAEA91FF86
    - pgp: FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4
destination_rules:
    - s3_bucket: "sops-publish-functional-tests"
      s3_prefix: "functional-test/"
      path_regex: test_encrypt_publish_s3.json
      reencryption_rule:
        pgp: B611A2F9F11D0FF82568805119F9B5DAEA91FF86
    - vault_path: "functional-test/"
      path_regex: test_encrypt_publish_vault.json
